### ISSUE TITLE
Why use python 2.X instead of python 3.X ? doesn't make any sense

### ISSUE THREAD

**Issue by developeralgo8888** [zhongwen/predictron#4] opened 2017-01-10 07:35 UTC
Note: This will not run in Python 3.X  or tensorflow 0.12

**Comment by zhongwen** [comment] 2017-01-10 09:33
Hi, Please try tensorflow 0.12.1, following the installation instruction of https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/get_started/os_setup.md . By using 

```
# Ubuntu/Linux 64-bit, GPU enabled, Python 2.7
# Requires CUDA toolkit 8.0 and CuDNN v5. For other versions, see "Installing from sources" below.
$ export TF_BINARY_URL=https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow_gpu-0.12.1-cp27-none-linux_x86_64.whl
```

On the compatibility of py3, I will look into this issue and get back to you later.

**Comment by zhongwen** [comment] 2017-01-11 21:56
Could you please give me a PR of your py2&3 compatible version when it is finished?

**Comment by developeralgo8888** [comment] 2017-01-12 04:24
I did upgrade my tensorflow to r1.0a from r0.12.0 and python 3.5  and made python 3 modifications to try and run but i am getting 

File "./train_multigpu.py", line 250, in <module>
    tf.app.run()
  File "/home/anaconda3/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "./train_multigpu.py", line 246, in main
    train()
  File "./train_multigpu.py", line 146, in train
    **maze_ims_splits = tf.split(0, FLAGS.num_gpus, maze_ims_ph)**
  File "/home/anaconda3/lib/python3.5/site-packages/tensorflow/python/ops/array_ops.py", line 1570, in split
    split_dim=axis, num_split=num_or_size_splits, value=value, name=name)
  File "/home/anaconda3/lib/python3.5/site-packages/tensorflow/python/ops/gen_array_ops.py", line 3545, in _split
    num_split=num_split, name=name)
  File "/home/anaconda3/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 509, in apply_op
    (prefix, dtypes.as_dtype(input_arg.type).name))
TypeError: Input 'split_dim' of 'Split' Op has type float32 that does not match expected type of int32.

**Comment by zhongwen** [comment] 2017-01-12 04:36
H, the issue is caused by the API change,

from r0.12.1's
```
tf.split(split_dim, num_split, value, name='split')
```

to r1.0alpha's
```
tf.split(value, num_or_size_splits, axis=0, num=None, name='split')	
```

You may modify it into your TF version's API accordingly.

**Comment by developeralgo8888** [comment] 2017-01-12 04:55
i modified it and it seems to be running now in Python 3.5 and TF 1.0a . i am testing it with 
python ./train_multigpu.py   --max_depths=16   --batch_size=128   --num_gpus=8

i have 8 Titan X GPUs

is this fine or i need to modify it

**Comment by zhongwen** [comment] 2017-01-12 04:57
if you have 8 GPUs in a single machine, it will work, otherwise, you can modify the `num_gpus`. Also the `max_depth` could be reduced if you would like the program run a bit faster.

**Comment by developeralgo8888** [comment] 2017-01-12 04:59
it is OK, the dev machine , i have can run as long as it wants .is there a way to view the progress with tensorboard or how do i view the results or progress

**Comment by zhongwen** [comment] 2017-01-12 05:02
you can view it in the tensorboard with 

`tensorboard --logdir=./ckpts/predictron_train`

Also, it will print out logs on the screen. 

You may add more summaries op to view more statistics on the tensorboard, or logging more information. Just modify it.

**Comment by developeralgo8888** [comment] 2017-01-12 05:02
It was running fine but it threw an error after a couple of cycles

Traceback (most recent call last):
  File "./train_multigpu.py", line 252, in <module>
    tf.app.run()
  File "/home/anaconda3/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "./train_multigpu.py", line 248, in main
    train()
  File "./train_multigpu.py", line 183, in train
    apply_gradient_op = opt.apply_gradients(grad_vars, global_step=global_step)
  File "/home/anaconda3/lib/python3.5/site-packages/tensorflow/python/training/optimizer.py", line 409, in apply_gradients
    self._create_slots(var_list)
  File "/home/anaconda3/lib/python3.5/site-packages/tensorflow/python/training/adam.py", line 119, in _create_slots
    self._zeros_slot(v, "m", self._name)
  File "/home/anaconda3/lib/python3.5/site-packages/tensorflow/python/training/optimizer.py", line 609, in _zeros_slot
    named_slots[var] = slot_creator.create_zeros_slot(var, op_name)
  File "/home/anaconda3/lib/python3.5/site-packages/tensorflow/python/training/slot_creator.py", line 123, in create_zeros_slot
    colocate_with_primary=colocate_with_primary)
  File "/home/anaconda3/lib/python3.5/site-packages/tensorflow/python/training/slot_creator.py", line 101, in create_slot
    return _create_slot_var(primary, val, '')
  File "/home/anaconda3/lib/python3.5/site-packages/tensorflow/python/training/slot_creator.py", line 55, in _create_slot_var
    slot = variable_scope.get_variable(scope, initializer=val, trainable=False)
  File "/home/anaconda3/lib/python3.5/site-packages/tensorflow/python/ops/variable_scope.py", line 987, in get_variable
    custom_getter=custom_getter)
  File "/home/anaconda3/lib/python3.5/site-packages/tensorflow/python/ops/variable_scope.py", line 889, in get_variable
    custom_getter=custom_getter)
  File "/home/anaconda3/lib/python3.5/site-packages/tensorflow/python/ops/variable_scope.py", line 347, in get_variable
    validate_shape=validate_shape)
  File "/home/anaconda3/lib/python3.5/site-packages/tensorflow/python/ops/variable_scope.py", line 332, in _true_getter
    caching_device=caching_device, validate_shape=validate_shape)
  File "/home/anaconda3/lib/python3.5/site-packages/tensorflow/python/ops/variable_scope.py", line 656, in _get_single_variable
    "VarScope?" % name)
ValueError: Variable state/conv1/weights/Adam/ does not exist, or was not created with tf.get_variable(). Did you mean to set reuse=None in VarScope?

**Comment by zhongwen** [comment] 2017-01-12 05:05
Well, something might have changed in r1.0 alpha. 

If it is possible, could you please use r0.12.1 ? Or I will look into the r1.0 in the near future. Originally i planned to upgrade it to match r1.0, but until the official release intead of the current alpha version.

**Comment by developeralgo8888** [comment] 2017-01-19 02:23
I tried it with TF r0.12.1 and Python 3.5 but i am getting the same error .

**Comment by zhongwen** [comment] 2017-01-19 02:30
I will look into this.

**Comment by developeralgo8888** [comment] 2017-01-19 02:57
i have a few hours to run the predictron. Can you have a look , please

**Comment by zhongwen** [comment] 2017-01-19 03:22
I am looking into this issue. Thanks.

**Comment by zhongwen** [comment] 2017-01-19 05:37
Hi, 

please have a look at the branch of [py3](https://github.com/zhongwen/predictron/tree/py3). To ensure we have the same environment, please use https://github.com/zhongwen/predictron/blob/py3/tf_py3.yml to create your conda environment. (by modifying `your_user_name` in the last line 
`prefix: /home/your_user_name/anaconda3/envs/tensorflow`. 

This essentially follows the exact instructions step-by-step on the [TensorFlow installation webpage](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/get_started/os_setup.md#anaconda-installation). 

Here is some log of my run, it runs normally. 

```
INFO:multigpu_train:2017-01-19 13:35:49.161376: step 1880, loss = 0.0992, loss_preturns = 0.0302, loss_lambda_preturns = 0.0194 (793.6 examples/sec; 0.161 sec/batch)
INFO:multigpu_train:2017-01-19 13:35:51.549731: step 1890, loss = 0.1024, loss_preturns = 0.0335, loss_lambda_preturns = 0.0178 (352.7 examples/sec; 0.363 sec/batch)
INFO:multigpu_train:2017-01-19 13:35:53.517329: step 1900, loss = 0.1228, loss_preturns = 0.0379, loss_lambda_preturns = 0.0235 (326.7 examples/sec; 0.392 sec/batch)
INFO:multigpu_train:2017-01-19 13:35:55.050952: step 1910, loss = 0.0828, loss_preturns = 0.0262, loss_lambda_preturns = 0.0152 (1407.7 examples/sec; 0.091 sec/batch)
INFO:multigpu_train:2017-01-19 13:35:56.892554: step 1920, loss = 0.0910, loss_preturns = 0.0291, loss_lambda_preturns = 0.0163 (944.1 examples/sec; 0.136 sec/batch)
```

**Comment by zhongwen** [comment] 2017-01-19 23:21
If you still met the error, please reopen this issue. I am closing it now.

**Closed as completed by zhongwen** 2017-01-19 23:21 UTC
